module.exports = {
  configFTP: {
    host: "23.236.48.59",
    port: 22,
    user_name: "name",
    password: "password",
    root_directory: "/your/dir/",
    csv_name: "csv_name",
  },
  configGSH: {
    client_email: "email",
    private_key: "key",
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
    spreadsheetIdGoogle: "id",
    spreadsheetIdFacebook: "id",
    sheetName: "name",
  },
  configValidateCSV: {
    columnsAddToBeginningGoogle: ["unique_id", "reporting_label"],
    columnsAddToEndGoogle: ["is_active", "is_default"],
    columnsAddToBeginningFacebook: ["hotel_id"],
    columnsAddToEndFacebook: ["visibility"],
    columnsToSave: {
      origin: 0,
      destination: 1,
      hotel_id: 2,
      name: 3,
      address_country: 8,
      base_price: 14,
      package_price: 15,
      description: 16,
      short_description: 17,
      trip_length_of_stay: 18,
      thumbnail_image_url: 20,
      url: 21,
      DepartureLowDate: 22,
      DepartureHightDate: 23,
      PackageTypeCode: 25,
      NativeDescription: 28,
      AllInclusive: 29,
    },
  },
};
